// libs/angular/mouse-events-have-key-events/src/lib/mouse-events-have-key-events.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'eslint-a11y-demo-mouse-events-have-key-events',
  template: `
    <section>
      <!-- mouseover/mouseout paired with focus/blur -->
      <div (mouseover)="onMouseOver()" (focus)="onFocus()">
        mouseover with focus
      </div>
      <div (mouseout)="onMouseOut()" (blur)="onBlur()">mouseout with blur</div>
      <div
        (mouseover)="onMouseOver()"
        (focus)="onFocus()"
        (mouseout)="onMouseOut()"
        (blur)="onBlur()"
      >
        mouseover with focus and mouseout with blur
      </div>
    </section>

    <section>
      <!-- cannot be configured to work with custom components -->
      <my-custom-button (mouseover)="onMouseOver()">
        Custom Button
      </my-custom-button>
    </section>
  `,
  styleUrls: ['./mouse-events-have-key-events.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MouseEventsHaveKeyEventsComponent {
  onMouseOver(): void {
    //
  }

  onFocus(): void {
    //
  }

  onMouseOut(): void {
    //
  }

  onBlur(): void {
    //
  }
}

// libs/react/mouse-events-have-key-events/src/lib/react-mouse-events-have-key-events.tsx
import styles from './react-mouse-events-have-key-events.module.scss';

/* eslint-disable-next-line */
export interface ReactMouseEventsHaveKeyEventsProps {}

export function ReactMouseEventsHaveKeyEvents(
  props: ReactMouseEventsHaveKeyEventsProps
) {
  function onMouseOver() {
    //
  }
  function onMouseOut() {
    //
  }
  function onFocus() {
    //
  }
  function onBlur() {
    //
  }

  return (
    <section>
      <p>mouseover/mouseout paired with focus/blur:</p>
      <div onMouseOver={onMouseOver} onFocus={onFocus} tabIndex={0}>
        mouseover with focus
      </div>
      <div onMouseOut={onMouseOut} onBlur={onBlur} tabIndex={0}>
        mouseout with blur
      </div>
      <div
        onMouseOver={onMouseOver}
        onFocus={onFocus}
        onMouseOut={onMouseOut}
        onBlur={onBlur}
        tabIndex={0}
      >
        mouseover with focus and mouseout with blur
      </div>
    </section>
  );
}

export default ReactMouseEventsHaveKeyEvents;
